apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-autoscaling
  labels:
    app: my-k8s-deployment
spec:
  selector:
    matchLabels:
      project: qwe
  template:
    metadata:
      labels:
        project: qwe # Service will look for those PODs labels
    spec:
      containers:
      - name: qwe-web
        image: adv4000/k8sphp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-web-deployment-autoscaling #same name with deployment
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-autoscaling-pod-service
  labels:
    env: prod
    owner: DenisAnanev
spec:
  selector:
    project: qwe # Selecting PODs with thoise Labels
  ports:
    - name: app-listener
      protocol: TCP
      port: 80 #Port on LoadBalancer
      targetPort: 80 #Port on POD
  type: LoadBalancer

