apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-multi-pod
  labels:
    app: my-k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: elor
  template:
    metadata:
      labels:
        project: elor
    spec:
      containers:
      - name: my-web
        image: adv4000/k8sphp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        
      - name: not-my-web
        image: tomcat:8.5.38
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
#=====================SERVICE==================
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: LoadBalancer
  selector:
    project: elor
  ports:
    - name: my-web-app-listener
      protocol: TCP
      port: 80 #Port on LoadBalancer
      targetPort: 80 #Port on POD

    - name: not-my-web-app-listener
      protocol: TCP
      port: 8888
      targetPort: 8080

      

