apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-practimce
spec:
  selector:
    matchLabels:
      app: k8s-practice
  template:
    metadata:
      labels:
        app: k8s-practice
    spec:
      containers:
      - name: k8s-practice
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
