apiVersion: v1
kind: Pod
metadata:
  name: my_web
  labels:
    env: prod
    app: main
    tier: frontend
    owner: DenisAnanev
spec:
  containers:

  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

  - name: apache
    image: httpd:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080