apiVersion: apps/v1
#===================DEPLOYMENT===================
kind: Deployment
metadata:
  name: my-web-deployment-replicas #name for deployment
  labels:
    app: my-k8-app
    env: prod
    owner: DenisAnanev
#==========spec==================================
spec:
  replicas: 3
  selector: #which pods this deployment would work
    matchLabels:
      project: elor #required to match with that labels which you want to attach deployment
#==================POD========================
  template:
    metadata:
      labels:
        project: elor #label for pod, required to match with label in spec
    spec:
      containers:
      - name: elor-web #name for pod
        image: nginx:latest #image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
