apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    # resources:
    #   limits:
    #     cpu: 500m
    #     memory: 512Mi
    #   requests:
    #     cpu: 500m
    #     memory: 512Mi
    args:
    - /bin/bash
    - -c
    - |
      apt-get update
      apt-get install stress
      apt-get install memtester
      apt-get install curl
      while true; do
        curl localhost
      done
  restartPolicy: Always