apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app: my-k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: susel
  template:
    metadata:
      labels:
        project: susel #service look for this label
    spec:
      containers:
      - name: susel-web
        image: adv4000/k8sphp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
