#kubectl apply -f l2-advertisement.yml 
#kubectl -n metallb-system get l2advertisement
#NAME               IPADDRESSPOOLS   IPADDRESSPOOL SELECTORS   INTERFACES
#l2-advertisement   ["first-pool"] 
                            
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool