apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web2-deployment
  labels:
    app: my-k8s2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: susel2
  template:
    metadata:
      labels:
        project: susel2 #service look for this label
    spec:
      containers:
      - name: susel2-web
        image: adv4000/k8sphp:version2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
